import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import { NavbarDemo } from "@/components/navbar";
import { Toaster } from "react-hot-toast";
import { KeepItSafeContractProvider } from "@/hooks/useKeepItSafe";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Keep It Safe",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className={inter.className}>
        <KeepItSafeContractProvider>
          <Providers>
            <NavbarDemo />
            <Toaster position="top-center" />
            {children}
          </Providers>
        </KeepItSafeContractProvider>
      </body>
    </html>
  );
}
